### ISSUE TITLE
Support CUDA 10 and its new features

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/cuda-api-wrappers#77]
Well, CUDA 10 is out and the wrappers don't yet support any of the new functionality (even if the changes are not earth-shattering).

What needs to be addressed, in general:

* [ ] Issue #175: Task graphs: Representation, capturing, manipulation, scheduling.
* [x] Issue #179: Use of `cudaLaunchHostFunc()` instead of enqueuing callbacks (but callbacks run on error as well... what should the behavior be?)	
* [ ] External memory objects, external semaphore objects etc.
* [ ] NTVX v3 novelties.

Specific blocking issues:

* [x] Issue #78 - some cudaPointerAttributes members deprecated in CUDA 10

and perhaps other things I've missed.

**Comment by codecircuit** [comment]
The graph based execution model might be nice!

**Comment by eyalroz** [comment]
@codecircuit : Yes, it would be nice. The thing is, I would need to either write my on lightweight C++'ish graph library, or adapt an existing one - and that's no small challenge.

**Comment by eyalroz** [comment]
We have the milestone, so this issue is redundant.
